#pragma once

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define SCREEN_WIDTH 525
#define SCREEN_HEIGHT 508

#define MAX_FRAME_RATE 120

#define TILE_SIZE 32
#define BRICK_WIDTH 16

#define TILEMAP_TRANSPARENT_COLOR		D3DCOLOR_XRGB(5,5,5)


